### DISCUSSION TITLE
Parallel consumer pods monitoring by Kubernetes

### DISCUSSION THREAD

**Discussion by neurodev26** [confluentinc/parallel-consumer#403] [Q&A]
Hi,
We are using Kubernetes to orchestrate parallel consumer pods. I know it's not perfect for Kafka consumer auto scaling but at least we want to get pods auto created if PC is leaving the consumer group with below exception. Currently the issue I am facing is - with this exception the app is not shutdown and the health endpoints are still alive so Kubernetes does not replace the pod which is not registered or subscribed to any of the partitions.

`Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: Timeout waiting for commit response PT30S to request ConsumerOffsetCommitter.CommitRequest(id=xxxxxx, requestedAtMs=xxxxx)`

Would really appreciate any help on this!

Thanks in advance.

**Comment by neurodev26** [comment]
Implement custom `HealthIndicator` and return 503 on `ParallelEoSStreamProcessor.isClosedOrFailed`. 
For example :

```
import com.jpatel.test.confluent.kafka.ParallelConsumer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.actuate.health.HealthIndicator;
import org.springframework.stereotype.Component;

@Component("pcHealthIndicator")
public class PCHealthIndicator implements HealthIndicator {

    @Autowired
    private ParallelConsumer parallelConsumer;

    @Override
    public Health health() {
        if (parallelConsumer.getParallelStreamProcessor().isClosedOrFailed()) {
            logger.warn("PCHealthIndicator :: health reports parallel consumer is closed or failed" +
                    " nr of assigned partitions {} , failure root cause {} , "
                    , parallelConsumer.getParallelStreamProcessor().getNumberOfAssignedPartitions()
                    , parallelConsumer.getParallelStreamProcessor().getFailureCause()
                    , parallelConsumer.getParallelStreamProcessor().getMyId()
            );
            return Health.down().build();
        } else {
            logger.debug("PCHealthIndicator :: health reports parallel consumer is still up" +
                            " nr of assigned partitions {} , failure root cause {} , ids {}"
                    , parallelConsumer.getParallelStreamProcessor().getNumberOfAssignedPartitions()
                    , parallelConsumer.getParallelStreamProcessor().getFailureCause()
                    , parallelConsumer.getParallelStreamProcessor().getMyId()
            );
            return Health.up().build();
        }
    }
}

```

Expose to spring health management

```
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,liveness,readiness
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    group:
      readiness:
        include: pcHealthIndicator
      liveness:
        include: pcHealthIndicator
```

Change kubernetes liveliness endpoint to pcHealthIndicator in terraform module

```
  readiness_probe_path   = "/actuator/health/readiness"
  liveness_probe_path    = "/actuator/health/pcHealthIndicator"
```
